### ISSUE TITLE
source code missing

### ISSUE THREAD

**Issue by fcauwe** [wojked/dust-sensor#5]
I would love to try to build the same sensor, but i'm missing the source code.
Can you also publish it?

**Comment by wojked** [comment]
This is a code of the case, firmware is another project:
https://github.com/letscontrolit/ESPEasy

**Comment by wojked** [comment]
If you need more info please visit my website that describes the configuration process as there is no need to build anything from the firmware source code, just clicking through the web panel:
https://dustsensor.net/firmware/
